### ISSUE TITLE
Navigation buttons shifting on various pages

### ISSUE THREAD

**Issue by rgovindjee** [ahscpc/ahscpc.github.io#10]
When navigating from either the homepage or "Monthly Challenges", there is a noticeable shift in the position of the navigation bar.

https://i.gyazo.com/8e673704a30fff0f90a4a4c6de03192c.gif

**Comment by realcake** [comment]
https://gyazo.com/dccd88b7bcb87fe66b6617206c80a71b

Its because of the side scroll thing, it's shifting it.
