### ISSUE TITLE
Spelling and Grammar on the homepage

### ISSUE THREAD

**Issue by rgovindjee** [ahscpc/ahscpc.github.io#11]
In the sentence "Meetings are every thursday at lunch in room 502. In order to join, come to a meeting. No prior knowlege of computer programming is required for membership.", Thursday should be capitalized, and "knowlege" should be spelled "knowledge".

**Comment by realcake** [comment]
Noted, and fixed.

https://gyazo.com/a69286d9e14c29910c391e7b57f458f8

**Comment by ahyattdev** [comment]
Why was this reopened? He fixed the issue.
