### ISSUE TITLE
Naming of the folder "resources"

### ISSUE THREAD

**Issue by rgovindjee** [ahscpc/ahscpc.github.io#12]
The folder name "resources" is usually reserved for assets such as art, logos, etc. but is in use for a page, possibly leading to confusion. Recommend renaming or dispensing of the folder system entirely, instead having index.html, resources.html, and challenges.html.

**Comment by ahyattdev** [comment]
Good suggestion, I'll handle this during my CS class today.

**Comment by ahyattdev** [comment]
Fixed by 9b9e6c1785a211c6f29cbef9389a09c553db5005
