### ISSUE TITLE
Possible animation for the homepage, thoughts?

### ISSUE THREAD

**Issue by realcake** [ahscpc/ahscpc.github.io#13]
https://gyazo.com/248c17d9e2070fe6a5356974acda73ba

Yes, it uses key frames, but it's necessary, unless someone has another way.

**Comment by rgovindjee** [comment]
How about this one? https://drive.google.com/file/d/0B-_rMopq96srajBsRXh0VnZWWkk/view?usp=sharing
Animations are generally resource-intensive, and not great for lower-end machines--just something to think about.

**Comment by realcake** [comment]
I don't know, that one looks like it was made in blender, I would prefer: https://www.youtube.com/watch?v=bYDJF33Fi5E&feature=youtu.be

**Comment by ahyattdev** [comment]
Looks good, older machines can suffer.
