### ISSUE TITLE
Absolute (root-relative) URLs 

### ISSUE THREAD

**Issue by rgovindjee** [ahscpc/ahscpc.github.io#24]
All assets and links to other pages currently use what are basically absolute URLs (e.g /assets/logo.png -> http://ahscpc.github.io/assets/logo.png) instead of relative ones (e.g. assets/logo.png -> [domain]/assets/logo.png). This makes it difficult (impossible?) to test locally or move anywhere else, perform maintenance,  and seems to be poorly suited for most projects. I recommend switching to relative URLs for the navigation, assets, and stylesheet.

**Comment by ahyattdev** [comment]
> its <current year>
> using file:// to test locally


> e.g /assets/logo.png -> http://ahscpc.github.io/assets/logo.png)
 
Root relative URLs are still domain agnostic, it does not indicate a domain name like the example you gave suggests. 

This seems like a good change to make, but it has a low priority as it fixes a problem we don't have. I can't work on the site until I get home ok Monday, so someone else can make this change.

**Comment by rgovindjee** [comment]
I had already made the change, but it was reverted. I will submit a pull request again later.

**Comment by realcake** [comment]
Alright, if you submit the request, I will merge it.

**Comment by ahyattdev** [comment]
This has been fixed by eca8b557b271b368798c91372e6da4888151e888
